### ISSUE TITLE
clinet.recipient.get is not a function

### ISSUE THREAD

**Issue by LukeXF** [PaymentRails/javascript-sdk#13]
Hey again,

1. In the API documentation for [creating a client](https://docs.paymentrails.com/api/#create-a-recipient), the word `client` has a typo `clinet`, 
2. After I fixed the typo, I got `client.recipient.get is not a function`. 

Looking through your [RecipientGateway.ts](https://github.com/PaymentRails/javascript-sdk/blob/c3121c6/lib/RecipientGateway.ts#L58) I see you're using `.find` and not `.get`.

Your GitHub documentation has [find](https://github.com/PaymentRails/javascript-sdk/blob/master/docs/classes/recipientgateway.md#find) correctly documented.

I'm happy to update the documentation (and help maintain) if it's open source. Will report anymore issues as I go.

![image](https://user-images.githubusercontent.com/6208873/73896528-25c3fd00-487b-11ea-89a0-126926b0c45d.png)

**Comment by fronugget** [comment]
Thanks for pointing this out 👍  Changes have been made to the docs.
