### ISSUE TITLE
Argument type {recipientId: *} is not assignable to parameter type string

### ISSUE THREAD

**Issue by LukeXF** [PaymentRails/javascript-sdk#14]
Retrieving all payments as shown on the [API documentation](https://docs.paymentrails.com/api/?javascript#retrieve-all-payments) shows I can provide an object as a parameter with `recipientId` inside of that.

```
const response = await client.payment.search({
    recipientId: "R-1a2B3c4D5e6F7g8H9i0J1k"
});
```

But my IDE displays error `Argument type {recipientId: *} is not assignable to parameter type string` when using this example.

Your [GitHub documentation](https://github.com/PaymentRails/javascript-sdk/blob/master/docs/classes/paymentgateway.md#search) and [PaymentGateway.ts#L106](https://github.com/PaymentRails/javascript-sdk/blob/c3121c6/lib/PaymentGateway.ts#L106) shows that it expects the first parameter, `batchId`, to be a string.

What is the correct functionality?

From API documentation:
![image](https://user-images.githubusercontent.com/6208873/73898049-f9f74600-487f-11ea-85dc-6bcc006abf72.png)

**Comment by fronugget** [comment]
The package was not updated on NPM, it should now be inline with docs
