### ISSUE TITLE
getting issue in error handling 

### ISSUE THREAD

**Issue by hasan-promact** [PaymentRails/javascript-sdk#2]
when try to do some action like add new recipent or create payment or create batch when there is some error it gives this error.
BaseException (/user_code/node_modules/paymentrails/dist/exceptions/index.js:9:5) at Malformed (/user_code/node_modules/paymentrails/dist/exceptions/index.js:30:5) at Request.err [as _callback] (/user_code/node_modules/paymentrails/dist/Client.js:36:36) at Request.self.callback (/user_code/node_modules/paymentrails/node_modules/request/request.js:185:22) at emitTwo (events.js:106:13) at Request.emit (events.js:191:7) at Request.<anonymous> (/user_code/node_modules/paymentrails/node_modules/request/request.js:1161:10) at emitOne (events.js:96:13) at Request.emit (events.js:188:7) at IncomingMessage.<anonymous> (/user_code/node_modules/paymentrails/node_modules/request/request.js:1083:12)

note : we are using js sdk in firebase functions

**Comment by koblas** [comment]
Do you know what version of node is running on firebase in your environment?

**Comment by hasan-promact** [comment]
Hello Thanks for reply 
its nodejs 6

**Comment by koblas** [comment]
Are you able to use the API outside of firebase on your local machine?  Trying to figure out if it's a node 6 problem or a general problem.

**Comment by hasan-promact** [comment]
not tried outside of firebase currently firebase supports node v6.11.5 only. can you please check as we are using this in functions only. Also we are not getting any error code just get error messages.

**Comment by Sheikh-Aman** [comment]
_closing because stale_
